@startuml

class Personaje{
+vida()
+mover()
+recibirDañio()
}

class Jugador{
+Link


}

class Link{
+atacar()
+defender()
+usarObjeto()
-Espada()
-Escudo()
-Arco()
-Bomba()
-Hechizo()
-Flecha()
-Mapa()
}

class Zelda{
+usarMagia()
}

class Ganon{
+ataqueOscuro()
+atacar()
+perseguir()
+dañio
}

class Enemigo{
+atacar()
+perseguir()
+dañio
}


class jefe{
+ataqueEspecial()
+atacar()
+perseguir()
+dañio

}

class Espada{
+dañio
+atacar()
}

class Escudo{
+defender()
}

class Arco{
+disparar()
+dañio()
+lanzar()
}

class Flecha{
+dañio
}

class Bomba{
+ explotar()
}

class Corazon{
+curar()
}

class Rupia{
+valor
}

class Llave{
+abrir()
}

class Cofre{
+abrir()
}

class Mazmorra{
+entrar()
+salir()
+Puerta()
-Cofre()
-Enemigo()
-jefe()
}

class Hechizo{
+lanzar()
+dañio()
}
class sistemalanzamiento{
+lanzar()

}


class Inventario{
+agregarObjeto()
+usarObjeto()
}

class Mapa{
+mostrar()
}

class Trifuerza{
+otorgarPoder()
+dañio()
}
class Puerta{
+abrirconllave()
}


Link --> Personaje
Zelda --> Personaje
Ganon --> Personaje
Enemigo --> Personaje

jefe --> Enemigo

Link "1"*--"1" Espada
Link  "1"*--"1" Escudo
Link "1"*--"1" Inventario
Link "1"*--"4" Corazon

Link "1"*--"99" Rupia
Link "1"o--"1"Arco
Link "1"*-- "20"Flecha
Link "1"*-- "10"Bomba
Link "1"*-- "5"Llave
Link "1"*-- "1"Mapa
Link "1"o--"1"Mapa
Link "1"*-- "5"Hechizo

Zelda "1"*-- "1"Trifuerza

Ganon "1"*-- "1"Trifuerza
Ganon "1"*-- "1"Hechizo

Mazmorra "1"*-- "5"Cofre
Mazmorra "1"*-- "8"Enemigo
Mazmorra "1"*-- "1"jefe
Mazmorra "1"*-- "5"Llave
Mazmorra "1"*--"5"Puerta

Cofre "1"*-- Rupia
Cofre "1"o-- Hechizo

@enduml the leyends of zelda